#!/bin/bash
guitool=zenity
tempdir="/tmp/.${USER}-audio-converter-$$"

exit_me(){
   rm -rf ${tempdir}
   exit 1
}

trap "exit_me 0" 0 1 2 5 15

LOCKFILE="/tmp/.${USER}-$(basename $0).lock"
[[ -r $LOCKFILE ]] && PROCESS=$(cat $LOCKFILE) || PROCESS=" "

if (ps -p $PROCESS) >/dev/null 2>&1
then
   echo "E: $(basename $0) is already running"
   $guitool --error --text="$(basename $0) is already running"
   exit 1
else
   rm -f $LOCKFILE
   echo $$ > $LOCKFILE
fi


# How many files to make the progress bar
PROGRESS=0
NUMBER_OF_FILES="$#"
let "INCREMENT=100/$NUMBER_OF_FILES"


mkdir -p "$tempdir"

# Creating thumbnails. Specific work on picture should be add there as convert's option
( 
   for i in "$@"
   do
echo "$PROGRESS"
file="$i"
filename="${file##*/}"
filenameraw="${filename%.*}"
echo -e "# Converting: \t ${filename}"

rm -rf "${tempdir}"
mkdir -p "${tempdir}"
cp "$file" "${tempdir}/first"
file="${tempdir}/first"

mplayer -quiet -vo null -vc null -af resample=44100 -ao pcm:waveheader:file="${tempdir}/second.wav" ${file}
oggenc -Q ${tempdir}/second.wav -o ${tempdir}/third.ogg
cp "${tempdir}/third.ogg" "${filenameraw}.ogg"
rm -rf "${tempdir}"

let "PROGRESS+=$INCREMENT"
done
) | $guitool  --progress --title "Converting files..." --percentage=0 --auto-close --auto-kill

rm -rf ${tempdir}
